### ISSUE TITLE
Problem: "CHAIN SHOT" from Monthly ASCII 1985-11, No.101

### ISSUE THREAD

**Issue by gingerbeardman** [captainys/77AVEMU#7]
does not run correctly
1. header graphics using GET@ and PUT@ does not display correctly
2. machine code section of BASIC listing gets stuck in a loop

comparison
- works OK with XM7

Let me know if I can be of assistance!

## MATSU screen recording

https://github.com/captainys/77AVEMU/assets/49612/6a4189fb-8ba7-4e50-b229-4b267d84275f

## XM7 screen recording

https://github.com/captainys/77AVEMU/assets/49612/151b9ad0-fe2f-481a-85f5-43c58cb0a95e

## reference screenshots

1. https://web.archive.org/web/19981201034336/http://www.asahi-net.or.jp/%7EKY6K-MRB/chainsht.htm
![](https://web.archive.org/web/19981201034336im_/http://www.asahi-net.or.jp/~KY6K-MRB/chainsht.gif)
2. https://www.asahi-net.or.jp/~ky6k-mrb/chainsht.htm
![](https://www.asahi-net.or.jp/~ky6k-mrb/chainimg.gif)

**Comment by captainys** [comment]
Thank you for the report?  Is there anywhere I can download the program?

Also the program looks to be written for F-BASIC V3.0.  Can you try it from V3.0 instead of V3.3?  V3.3 is internally very different from V3.0.

Thanks!

**Comment by gingerbeardman** [comment]
I typed in the listing myself from Monthly ASCII 1985.

The game works fine in F-BASIC 3.3 on XM7, so it seems compatible?

Nevertheless, I'll try it in FBASIC 3.0.

**Comment by gingerbeardman** [comment]
Yes! Good results for _Chain Shot_.

- 77AVEMU using F-BASIC 3.0 = WORKS
- 77AVEMU using F-BASIC 3.3 = BROKEN

- XM7 using F-BASIC 3.0 = WORKS
- XM7 using F-BASIC 3.3 = WORKS

So, I think there is a problem with 77AVEMU and F-BASIC 3.3

Thanks for your help!

**Comment by gingerbeardman** [comment]
I received your email.

I have also corrected some words in this thread :)
